baseURL = "http://blog.certseeds.com"
languageCode = "en-us"
title = "Certseeds Blog"
theme = "PaperMod"
Copyright = "Certseeds publish this document based on CC BY-NC-SA 4.0(or any later version)"
enableEmoji = true
hasCJKLanguage = true
enableRobotsTXT = true
enableInlineShortcodes = true
buildDrafts = false
buildFuture = false
buildExpired = false

[permalinks]
post = "/:title/"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Certseeds Blog"
description = "Certseeds Blog"
keywords = ["Blog", "Portfolio", "PaperMod"]
author = "Certseeds"
images = ["https://avatars.githubusercontent.com/u/51754303"]
DateFormat = "2006 January 2"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowFullTextinRSS = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

[params.assets]
disableHLJS = false
disableFingerprinting = true
favicon = "https://avatars.githubusercontent.com/u/51754303?s=40"
favicon16x16 = "https://avatars.githubusercontent.com/u/51754303?s=16"
favicon32x32 = "https://avatars.githubusercontent.com/u/51754303?s=32"
apple_touch_icon = "https://avatars.githubusercontent.com/u/51754303?s=24>"
safari_pinned_tab = "https://avatars.githubusercontent.com/u/51754303?s=24"

[params.label]
text = "Home"

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Certseeds"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives/"
weight = 10

[[menu.main]]
name = "posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "rss"
name = "rss"
url = "/index.xml"
weight = 10

[[menu.main]]
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "encryptMsg"
name = "encryptMsg"
url = "https://openpgpage.certseeds.com"
weight = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "monokai"
lineNos = false
noClasses = true
codeFences = true
guessSyntax = true
anchorLineNos = false
