name: github pages

on:
  push:
    branches: [ "master" ] # TODO
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: move files to content
        run: |
          mkdir -p ./content/posts
          mv ./2021 ./content/posts/
          mv ./2022 ./content/posts/
          mv ./LICENSE.md ./content/posts/
          mv ./README.md ./content/posts/
          mv ./README.words.md ./content/posts/

      - name: archive
        run: |
          echo '---' > ./content/archives.md
          echo 'title: "Archive"' >> ./content/archives.md
          echo 'layout: "archives"' >> ./content/archives.md
          echo 'summary: "archives"' >> ./content/archives.md
          echo '---' >> ./content/archives.md
      - name: search
        run: |
          echo '---' > ./content/search.md
          echo 'title: "Search"' >> ./content/search.md
          echo 'layout: "search"' >> ./content/search.md
          echo 'summary: "search"' >> ./content/search.md
          echo 'placeholder: "2022? 2021? 2077?"' >> ./content/search.md
          echo '---' >> ./content/search.md

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1